### ISSUE TITLE
Object & character highlighting

### ISSUE THREAD

**Issue by StevieGoodman** [CMP2804/Assessment2#12]
# Summary
We should clearly communicate the position of the player character, enemy characters & important objects through the usage of colour theory.

## Subtasks
- [x] Player character highlighting
- [x] Enemy character highlighting
- [x] Important object highlighting

# Intended outcome
- GameObjects can have a `ColourFillHighlighter` component attached to them
- The effect can be temporarily disabled (for example, before the player has received an upgrade)

**Comment by Vesper-Works** [comment]
![Image](https://user-images.githubusercontent.com/59376295/220427433-01bc6b2b-eee0-4abf-81e3-1c576690cd59.png)



Here's this object, which is usually yellow-ish, is now red due to the addition of the "ObjectHighlighter" component.

**Comment by Vesper-Works** [comment]
Waiting on player character model to create the player highlighter
